name: Publish a release

on:
  workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    environment: release

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout presto source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRESTODB_CI_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
          ref: master
          show-progress: false

      - name: Check branch
        if: ${{ github.ref != 'refs/heads/master' }}
        run: exit 1

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y bash build-essential git gpg python3 python3-venv

      - name: Configure Git
        run: |
          git config --global user.name ${{ vars.PRESTODB_CI_USER }}
          git config --global user.email ${{ vars.PRESTODB_CI_EMAIL }}

      - name: Determine Current Version
        id: get_version
        run: |
          REPO_CURRENT_VERSION=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -ntp -DforceStdout)
          echo "current_version=${REPO_CURRENT_VERSION}"
          echo "current_version=${REPO_CURRENT_VERSION}" >> $GITHUB_OUTPUT
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Prepare for Release
        run: |
          mvn release:prepare -B -DskipTests \
              -DautoVersionSubmodules=true \
              -DgenerateBackupPoms=false

          SCM_TAG=$(grep 'scm.tag=' release.properties | cut -d= -f2)
          echo "scm.tag=$SCM_TAG"
          echo $SCM_TAG > repo-release-tag.txt
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      - name: Save Release Tag
        id: save_tag
        run: |
          echo "RELEASE_TAG=$(cat repo-release-tag.txt)"
          echo "RELEASE_TAG=$(cat repo-release-tag.txt)" >> $GITHUB_OUTPUT

      - name: Import GPG Keys
        run: |
          echo "${{ secrets.OSS_GPG_SECRET }}" | base64 --decode | gpg --batch --import
          echo "${{ secrets.OSS_GPG_TRUST }}" | gpg --import-ownertrust
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
        env:
          OSS_GPG_SECRET: ${{ secrets.OSS_GPG_SECRET }}
          OSS_GPG_TRUST: ${{ secrets.OSS_GPG_TRUST }}

      - name: Release Artifacts to Maven Central
        run: |
          export SONATYPE_NEXUS_USERNAME=${{ env.SONATYPE_NEXUS_USERNAME }}
          export SONATYPE_NEXUS_PASSWORD=${{ env.SONATYPE_NEXUS_PASSWORD }}
          git checkout ${{ env.RELEASE_TAG }}
          mvn -s settings.xml -V -B -U -e -T2C deploy \
              -DautoReleaseAfterClose=true \
              -Dgpg.passphrase=${{ secrets.OSS_GPG_PASSPHRASE }} \
              -DkeepStagingRepositoryOnCloseRuleFailure=true \
              -DkeepStagingRepositoryOnFailure=true \
              -DskipTests \
              -Poss-release \
              -Pdeploy-to-ossrh \
              -DstagingProgressTimeoutMinutes=10
        env:
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          OSS_GPG_PASSPHRASE: ${{ secrets.OSS_GPG_PASSPHRASE }}
          JAVA_HOME: ${{ env.JAVA_HOME }}
          SONATYPE_NEXUS_USERNAME: ${{ vars.SONATYPE_NEXUS_USERNAME }}
          RELEASE_TAG: ${{ steps.save_tag.outputs.RELEASE_TAG }}

      - name: Push Git Tags
        run: |
          git push --follow-tags origin master
